### ISSUE TITLE
Maven few shot split

### ISSUE THREAD

**Issue by cnut1648** [chen700564/causalFSED#2]
Hi, interesting work!

I am wondering for processing maven files, it seems that `mavenpreprocess.py` is expecting a `.data` file while the MAVEN repo provides `.jsonl` file. What did you do to convert this? Thank you!

**Comment by chen700564** [comment]
It seems that something wrong in mavenpreprocess.py, so I have added the maven data in data/maven.

**Comment by cnut1648** [comment]
Thanks!
